export const FETCH_PLANETS_REQUESTED = 'FETCH_PLANETS_REQUESTED';
export const FETCH_PLANETS_SUCCESS = 'FETCH_PLANETS_SUCCESS';
export const FETCH_PLANETS_FAILED = 'FETCH_PLANETS_FAILED';

export const SEARCH_PLANETS_SERIES = 'SEARCH_PLANETS_SERIES';
