export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOG_OUT = 'LOG_OUT';
export const UPDATE_USER_CREDENTIALS = 'UPDATE_USER_CREDENTIALS';
export const USER_LOGIN_REQUESTED = 'USER_LOGIN_REQUESTED';
export const LOGIN_FAILED = 'LOGIN_FAILED';
